### ISSUE TITLE
Is it possible to rename the file before upload?

### ISSUE THREAD

**Issue by alanapradhan** [nervgh/angular-file-upload#138]

**Comment by hellsan631** [comment]
I want to just leave a solution here, because @nervgh 's comments didn't help at all for me. item.alias didn't work, and the docs/faq didn't help.

You need to change item.file.name, here is a small function that works well:

```js
uploader.onAfterAddingFile = function(item) {
        var fileExtension = '.' + item.file.name.split('.').pop();

        item.file.name = Math.random().toString(36).substring(7) + new Date().getTime() + fileExtension;
};
```

When you process the upload of the file, it should get renamed correctly. there is an item._file that has all of the original attributes that is used during the upload.

**Comment by AradhanaR** [comment]
Thanks @hellsan631 ... it worked for me!

**Comment by mfressdorf** [comment]
Thanks @hellsan631 :+1:

**Comment by IsraelSouza** [comment]
Not works on IE9.

**Comment by askdesigners** [comment]
There's a nastier problem here though in that you can have users uploading files with character that will break AWS links. Files like `!!měl být ekono()mic+=ký růst tažen^%&$$ 2.png` will not work at all. If it seems like a corner case, then you haven't dealt with real user files much. :) People do weird shit.

**Comment by tatsujb** [comment]
yes! 

I am in this case :

```
  /*
   * type false === image, true === document
   */
  addedFile(e, type) {
    const formData: FormData = new FormData();
    const File = e.addedFiles[0];
    const oldName = File.name;
    const fileExtension = oldName.slice(oldName.lastIndexOf('.') - oldName.length);
    const str = oldName.slice(0, oldName.lastIndexOf('.')).replace(/[^\w]/gi, '');
    Object.defineProperty(File, 'name', {
      writable: true,
      value: str + fileExtension
    });
    formData.append('files[]', File);
    if(type){
      this.api.uploadDocument(formData).subscribe();
    } else {
      this.api.uploadImage(formData).subscribe();
    }
  }
```

this fails because upload is somehow the variable File is just a pointer of some sort to actual computer file access and renaming it's name means that the File won't be found on the disk (without JS or angular errors, without any errors at all).

This is pretty stupid. 

I'm actually fine with renaming the user's file on disk before upload. the user is stupid and needs to have his hand held.

**Comment by fredyfx** [comment]
Thank you very much! @hellsan631

**Comment by Merlincool** [comment]
Okay I am struggling to understand this.

it would be glad if someone helps me here.

my file name is `My File @12345.txt`
this is file I want to upload
but I want this filename to be changed to `My File.txt` before it's uploaded, so server don't get that numerical values along with special character. Is that possible anyways?
