### ISSUE TITLE
Optional files

### ISSUE THREAD

**Issue by pjw91** [nervgh/angular-file-upload#151]
Expected: submitting the form even if `file` is null

Currently, if files are empty, then clicking submit will not work.

However, in some cases, the file is optional(not required), then `uploader.uploadAll()` will not submit the form, in
https://github.com/nervgh/angular-file-upload/blob/master/src/scripts/services/%24fileUploader.js#L213
`items.length`

Please add an option `optional{Boolean}` to indicate if the `file` can be optional.

Something like,
L213: (this.optional || items.length) && this.uploadItem(items[0]);

**Comment by arenddeboer** [comment]
Did you manage to make a pull request ? 
I am in the same boat, the file upload is optional and it seems like a logical choice to still submit the formdata using the same code path.

**Comment by injulkarnilesh** [comment]
I did, https://github.com/nervgh/angular-file-upload/pull/248
but it wasn't merged, because, i guess, it could be done without the changes from the merge.
I don't remember how I did it eventually, but by looking at the proposed changes from the pull request and the comment from  https://github.com/nervgh/angular-file-upload/issues/238#issuecomment-56783704  you should be able to do it.

**Comment by arenddeboer** [comment]
Thanks.
I am currently using your fork as I wasn't able to get it working by using any of the proposed solutions.
Will look into this further when time permits.
