### ISSUE TITLE
Фильтры

### ISSUE THREAD

**Issue by Ranerg** [nervgh/angular-file-upload#356]
Я так и не понял, что является первым аргументов для создания фильтра. Летит какой-то объект. Проблема в том, что при использовании элемента очереди в фильтрах не дает мне возможности использовать объект File, потому что передается объект. Есть ли решения?:)

**Comment by perpetuumstef** [comment]
Just in case some translation is needed :) "I did not understand, which is the first argument to create a filter. Flying an object <assuming this is dragging an object>. The problem is that when using the filter element in the queue does not allow me to use Object File, because the object is passed. Is there a solution? :)"

**Comment by nervgh** [comment]
@perpetuumstef , my applause :clap:

@Ranerg , the console will respond to your questions. You'll see [`{FileItem}`](https://github.com/nervgh/angular-file-upload/blob/v1.1.5/src/module.js#L762), where [`item._file`](https://github.com/nervgh/angular-file-upload/blob/v1.1.5/src/module.js#L786) is `{File}`. But you can use `fileItem.name` because [link](https://github.com/nervgh/angular-file-upload/blob/v1.1.5/src/module.js#L746)

**RU**
Юзай консоль, читай доки, смотри примеры и будет тебе счастье =)
