### ISSUE TITLE
Can not cancel upload onBeforeUploadItem.

### ISSUE THREAD

**Issue by andreaslarssen** [nervgh/angular-file-upload#425]
Canceling uploads in the 'onBeforeUpload' callback method still sends the request:

$scope.uploader.onBeforeUploadItem = function (item) {
    item.cancel();
}

Trying other FileItem methods produces same result:

$scope.uploader.onBeforeUploadItem = function (item) {
    item.remove();
}

...removes file from queue, but still sends the request.

**Comment by andreaslarssen** [comment]
Still no news on this? Others seeing the same? Have a work around?

**Comment by UltimateFighter** [comment]
i have the same problem. i will skip items there are not client valid. is there a solution?

**Comment by andreaslarssen** [comment]
@nervgh: Any idea why this would happen?

**Comment by markzolotoy** [comment]
Any progress on that one? Has anyone figured out how to cancel item upload?

**Comment by andreaslarssen** [comment]
New year, new possibilities?

**Comment by AnthonyLabaere** [comment]
Same issue.

**Comment by higordelgado** [comment]
Try  this
 $scope.uploader.cancelItem(item);

**Comment by markzolotoy** [comment]
I am also having a problem cancelling all items: uploader.cancelAll() after starting multiple file upload. It will cancel an item being currently uploaded, bu the rest of the queue is still uploading. Any idea?

**Comment by andreaslarssen** [comment]
@higordelgado Thanks for the tip, but it's still trying to upload the file.

**Comment by micobg** [comment]
I think that cancellig is not exactly what we want. Maybe the idea of canceling is to stop currently running uploading. But **uploadAll** method gets all items that are not already uploaded or currently uploading. So it doesn't check for canceled items.
One possible workaround is to remove the item from queue. **removeFromQueue** or **clearQueue** methods work fine called in **onBeforeUploadItem**.

**Comment by neuro-sys** [comment]
Another workaround for single queue fileuploads is to throw an exception which is silently get caught by FileUpload and cancels the upload.

**Comment by nervgh** [comment]
Fixed in `v2.3.3`

**Comment by tot-ra** [comment]
Still got this issue with v2.4.1 in IE v11, but now we've got two calls which generate two notifications in our app. That fix with dummy and two calls might be the problem and I can't debug it easily because its so async with next() and queue.

![2017-01-13 11_42_16-c__users_tactic_qa_pc_documents_app_source_bower_angular-file-upload_dist_angula](https://cloud.githubusercontent.com/assets/445122/21925396/fc743fda-d985-11e6-85ac-849b75fa174b.png)
![2017-01-13 11_41_25- rc-397 222 - tacticu2122 - internet explorer](https://cloud.githubusercontent.com/assets/445122/21925398/fc753458-d985-11e6-884c-34d24d587929.png)
![2017-01-13 11_41_38-c__users_tactic_qa_pc_documents_app_source_module_file_controller_multifileuploa](https://cloud.githubusercontent.com/assets/445122/21925397/fc745e16-d985-11e6-87bb-79f0bb3e0269.png)
![2017-01-13 11_40_59- rc-397 222 - tacticu2122 - internet explorer](https://cloud.githubusercontent.com/assets/445122/21925399/fc752256-d985-11e6-80a5-c9f54753a42d.png)

**Comment by nervgh** [comment]
@tot-ra "patch welcome"
