### ISSUE TITLE
 uploader.clearQueue() does not clear the input field

### ISSUE THREAD

**Issue by psibi** [nervgh/angular-file-upload#442]
This is similar to #166 

Two commenter's have already commented there that this issue is visible in the latest version.

I'm using 1.1.5 and can see this same issue.

**Comment by nervgh** [comment]
See [faq 4. "No file chosen" or "Re-add same file"](https://github.com/nervgh/angular-file-upload/wiki/FAQ#4-no-file-chosen-or-re-add-same-file)

**Comment by davidleureka** [comment]
From what I can tell, adding the "multiple" attribute to the file input control per your FAQ reference just makes it so that the control never shows the file name at all. I think what people want is for it to show the file name after you have picked the file. Then after you do the upload the file name should clear out. When the name stays there it gives the impression that the operation is not complete. Clearing it out helps the user understand that the process is done and they can upload another file.

Is that supported?

**Comment by brunobertechini** [comment]
+1

**Comment by gerome0123** [comment]
is there someone get this problem i dont understan the FAQ pleas give some example T_T
