### ISSUE TITLE
Is there an es5 branch? 

### ISSUE THREAD

**Issue by adamdva** [nervgh/angular-file-upload#488]
es6 is not supported in most browsers and that leaves this project now unusable.

**Comment by nervgh** [comment]
Last es5 tag [v2.0.1](https://github.com/nervgh/angular-file-upload/tree/v2.0.1).

Current branch are fully compatible with es5 because [babel](https://github.com/nervgh/angular-file-upload/blob/v2.1.1/package.json#L12) + [wepback](https://github.com/nervgh/angular-file-upload/blob/v2.1.1/package.json#L17) = es5 :yum:
See gulp [task](https://github.com/nervgh/angular-file-upload/blob/v2.1.1/gulpfile.js#L12).
