### ISSUE TITLE
Are parallel file uploads possible?

### ISSUE THREAD

**Issue by Danita** [nervgh/angular-file-upload#5]
Hi! Thanks for this module, looks great :smile: 

I was wondering if it's possible to upload all files simultaneously instead of one by one. If so, how do I configure the component?

**Comment by bushev** [comment]
Hi gyes!

It's possible to to upload several files simultaneously now? :-)

I have a very big latency with file processing (due to uploading to rackspace) and I can't force my users wait so much time. Rackspace support to 100 operation per a container per a second.

It would be a great feature of this uploader!

**Comment by wallstudios** [comment]
Any idea on when this feature will be included?
