### ISSUE TITLE
Selected file should replace existing in queue

### ISSUE THREAD

**Issue by petrkoutnycz** [nervgh/angular-file-upload#597]
I have following scenario:
1) input file is set to multiple="false"
2) set queue limit to 1
2) selected file no. 1
3) then selet file no. 2
4) the file no. 2 is refused because of the queue limit

But the existing file in queue should be replaced.

**Comment by nervgh** [comment]
Please, see that [link](https://github.com/nervgh/angular-file-upload/wiki/FAQ#4-no-file-chosen-or-re-add-same-file) and use search for related issues.

**Comment by petrkoutnycz** [comment]
The provided link is not related with issue I described earlier :-) I am talking about the state where I want to allow user upload single file. But if the user selects some file and then another, queue contains two items - which is wrong. The queue should contain only the last item. That is why I am not using multiple upload.

**Comment by jon64digital** [comment]
I don't know why the issue was closed. I don't think the author understood your problem.

Anyway, I faced a similar problem. This library is designed to work with a queue and is useful for uploading multiple files/galleries etc is excellent, but it falls down when you want an input to have a single file like a profile photo which overwrites the previous one if you want to choose a new file.

You can solve the problem like this though, don't set a queueLimit otherwise you won't be able to select a second file, then....

```
uploader.onAfterAddingFile = function(fileItem) {

    if(uploader.queue.length > 1){
        uploader.queue.splice(0, uploader.queue.splice.length -1);
    }

};
```

**Comment by petrkoutnycz** [comment]
That is exactly what I meant. I finally came up with the same solution. But I think it needs some correction anyway.

**Comment by gerome0123** [comment]
@jon64digital thanks man your a hero :)

**Comment by kacper-stolc-goyello** [comment]
Hi @nervgh, Thank you for your work. I think, however, that you misinterpreted the issue described here and the ticket should be reopened.
