### ISSUE TITLE
Upload a file in the controller without selecting it from template

### ISSUE THREAD

**Issue by einstyle** [nervgh/angular-file-upload#706]
Hi,
I have an image in the controller ($scope.img_test = 'my_image.png') and I want to upload it without click on the "select file" button in the template. Some ideas?

**Comment by jmjdesenvolvimento** [comment]
@einstyle but there will be an event to trigger(fire) the upload action?

**Comment by nervgh** [comment]
You could convert an Image to Blob and upload it.
See #208

**Comment by thrinay** [comment]
May I please know if this issue actually is rectified, because I tried inserting the blob and didn't actually work with an existing image in the controller. I do will attach here the image of what the desired result should look like, and any advice or help is much more appreciated
Just the existing image should be dragged to the uploader. This is what the desired result is

![screenshot from 2017-05-24 11-41-29](https://user-images.githubusercontent.com/9824922/27374538-8554cd02-566c-11e7-9c6f-e41ae205f40c.png)
